### PR TITLE
Update to 1.19

### PR DESCRIPTION
**Pull request by M8torr**
Updated:
- Fabric properties
- Fabric API version
- Loom version
- README.MD

Tested it on a Fabric 0.14.7 server with 1.19.

### CODE REVIEW

**Comment by legobmw99** [comment]
Did using the older Jar file not work by itself?

**Comment by M8torr** [comment]
I think it worked with the old .jar, just so it is available in modrinth marked compatible with 1.19

**Comment by legobmw99** [comment]
I've tested that the original 1.3.0 works with 1.19, so I've marked it as such in Modrinth and CF

**Comment by legobmw99** [comment]
I authorize the removal of this pull request from this repository's history

**Pull request closed without merging**
